git:
  diffRenderers:
    - name: delta
      command: delta --dark --paging=never
      colorArg: always
    - name: side-by-side
      command: delta --dark --paging=never --side-by-side
      colorArg: always
    - name: default
      type: rawGit
