# Data Catalog: 탐색과 노드 열기/닫기

[[keymaps.vim-tmux]]
keys = "j"
action = "data_catalog.cursor_down"

[[keymaps.vim-tmux]]
keys = "k"
action = "data_catalog.cursor_up"

[[keymaps.vim-tmux]]
keys = "h"
action = "data_catalog.toggle_node"

[[keymaps.vim-tmux]]
keys = "l"
action = "data_catalog.toggle_node"

# Results Viewer: 셀 이동

[[keymaps.vim-tmux]]
keys = "h"
action = "results_viewer.cursor_left"

[[keymaps.vim-tmux]]
keys = "j"
action = "results_viewer.cursor_down"

[[keymaps.vim-tmux]]
keys = "k"
action = "results_viewer.cursor_up"

[[keymaps.vim-tmux]]
keys = "l"
action = "results_viewer.cursor_right"

# Results Viewer: 페이지 이동

[[keymaps.vim-tmux]]
keys = "ctrl+d"
action = "results_viewer.cursor_page_down"

[[keymaps.vim-tmux]]
keys = "ctrl+u"
action = "results_viewer.cursor_page_up"

# Results Viewer: 테이블과 행의 경계로 이동

[[keymaps.vim-tmux]]
keys = "g"
action = "results_viewer.cursor_column_start"

[[keymaps.vim-tmux]]
keys = "G"
action = "results_viewer.cursor_column_end"

[[keymaps.vim-tmux]]
keys = "0,circumflex_accent"
action = "results_viewer.cursor_row_start"

[[keymaps.vim-tmux]]
keys = "dollar_sign"
action = "results_viewer.cursor_row_end"

# Results Viewer: 결과 탭 이동

[[keymaps.vim-tmux]]
keys = "H"
action = "results_viewer.previous_tab"

[[keymaps.vim-tmux]]
keys = "L"
action = "results_viewer.next_tab"
