package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
)

func loadConnections() (map[string]connection, error) {
	path, err := sourcePath()
	if err != nil {
		return nil, err
	}
	return readCatalog(path)
}

func renderCatalog(catalog map[string]connection) (map[string][]byte, error) {
	profiles := map[string]any{}
	rain := map[string]any{}
	lua := map[string][]string{}
	for _, id := range sortedKeys(catalog) {
		c := catalog[id]
		if contains(c.Tools, "harlequin") {
			profiles[strings.ReplaceAll(id, "-", "_")] = harlequinProfile(c)
		}
		if contains(c.Tools, "rainfrog") {
			rain[id] = rainfrogProfile(c)
		}
		if contains(c.Tools, "nvim") {
			lua[c.Project] = append(lua[c.Project], nvimEntry(c))
		}
	}
	outputs := map[string][]byte{}
	for name, value := range map[string]any{"harlequin.toml": map[string]any{"profiles": profiles}, "rainfrog_config.toml": map[string]any{"db": rain}} {
		data, err := encodeTOML(value)
		if err != nil {
			return nil, err
		}
		outputs[name] = append([]byte("# Generated by db sync. Do not edit.\n"), data...)
	}
	for project, lines := range lua {
		outputs[filepath.Join("nvim", project+".lua")] = []byte("-- Generated by db sync. Do not edit.\nreturn {\n" + strings.Join(lines, "\n") + "\n}\n")
	}
	return outputs, nil
}

func syncCatalog() (map[string]connection, error) {
	catalog, err := loadConnections()
	if err != nil {
		return nil, err
	}
	outputs, err := renderCatalog(catalog)
	if err != nil {
		return nil, err
	}
	root := filepath.Join(configBase(), "db")
	for _, name := range sortedKeys(outputs) {
		path := filepath.Join(root, name)
		existing, err := os.ReadFile(path)
		info, statErr := os.Lstat(path)
		if err == nil && statErr == nil && info.Mode().IsRegular() && info.Mode().Perm() == 0o600 && bytes.Equal(existing, outputs[name]) {
			continue
		}
		if err := writePrivate(path, outputs[name]); err != nil {
			return nil, err
		}
	}
	// Only remove our own retired Neovim outputs, never arbitrary user files.
	stale, err := filepath.Glob(filepath.Join(root, "nvim", "*.lua"))
	if err != nil {
		return nil, err
	}
	for _, path := range stale {
		if _, ok := outputs[filepath.Join("nvim", filepath.Base(path))]; ok {
			continue
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		if bytes.HasPrefix(data, []byte("-- Generated by db sync. Do not edit.\n")) {
			if err := os.Remove(path); err != nil {
				return nil, err
			}
		}
	}
	return catalog, nil
}
